# UTF-8格式
spring:
  profiles:
    active:
    - dev
---
spring:
  # 开发环境
  profiles: dev
  application: 
    name: config-xiong-dev
---
spring:
  # 测试环境
  profiles: test
  application: 
    name: config-xiong-test