spring:
  profiles:
    active:
      - dev
---
server:
  # 注册中心占用7001端口
  port: 7001 
spring:
  profiles: dev
  application:
    name: cloud-config-eureka
eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格
  client:
    # 当前的eureka-server自己不注册进服务列表中
    register-with-eureka: false
    # 不通过eureka获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: cloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
    defaultZone: http://eureka7001.com:7001/eureka/